// Uses the github.js API at https://github.com/michael/github.

// Globals
///////////////////

// The OAuth token was generated by WrinklyNinja with no scope
// (ie. public read-only). It's used to boost the request rate limit
// from 60/hour to 5000/hour.
auth = {
    token: "0c5d156093834990d28bfdbc2db9256f2e2ee352",
    auth: "oauth"
}

repos = [
    [ "Oblivion", "oblivion" ],
    [ "Skyrim", "skyrim" ],
    [ "Fallout 3", "fallout3" ],
    [ "Fallout: New Vegas", "falloutnv" ]
]

var github = new Github(auth);
var repoBranch = 'master';  //The repository branch to search.

var gameSelect = document.getElementById('gameSelectMenu');
var searchButton = document.getElementById('searchButton');
var searchBox = document.getElementById('searchBox');
var resultsDiv = document.getElementById('results');

// Functions
///////////////////

function isRegexEntry(name) {
    var end = name.substring(name.length - 5).toLowerCase();
    if (end == '\\.esp' || end == '\\.esm') {
        return true;
    }
}

function readMasterlist(err, data) {
    if (err !== null) {
        console.log(err);
        return;
    }

    var masterlist = jsyaml.safeLoad(data);
    document.getElementById('progress').classList.remove('show');

    /* Do search here. */
    console.log("Starting search.");
    if (masterlist.hasOwnProperty('plugins')) {
        for (var i in masterlist['plugins']) {
            var index = -1;
            if (isRegexEntry(masterlist["plugins"][i].name)) {
                if (RegExp(masterlist["plugins"][i].name, 'i').test(searchBox.value)) {
                    index = i;
                }
            } else if (masterlist["plugins"][i].name.toLowerCase().indexOf(searchBox.value.toLowerCase()) !== -1) {
                index = i;
            }
            if (index != -1) {
                console.log("Match: " + JSON.stringify(masterlist["plugins"][index]));
                var paperShadow = document.createElement('paper-shadow');
                paperShadow.setZ(1);
                var code = document.createElement('code');
                code.textContent = '  - ' + jsyaml.safeDump(masterlist["plugins"][index]).replace(new RegExp('\n', 'g'), '\n    ').trim();
                paperShadow.appendChild(code);
                resultsDiv.appendChild(paperShadow);
            }
        }
    }

    if (!resultsDiv.firstChild) {
        var elem = document.createElement('p');
        elem.textContent = "No matching entries found.";
        resultsDiv.appendChild(elem);
    }

    console.log("Search complete.");
}

function onSearchInit(evt) {

    if (evt.keyCode != 0 && evt.keyCode != 13) {
        return;
    }

    var repo = github.getRepo("loot", gameSelect.selected);
    repo.read(repoBranch, 'masterlist.yaml', readMasterlist);

    /* Clear any previous search results. */
    var progress = document.getElementById('progress');
    while (progress.nextElementSibling) {
        progress.parentElement.removeChild(progress.nextElementSibling);
    }

    console.log("Loading masterlist...");
    progress.classList.add('show');
}

// Startup Code
///////////////////

/* Fill the drop-down games box with stuff. */
for (var i=0; i < repos.length; ++i) {
    var option = document.createElement('paper-item');
    option.textContent = repos[i][0];
    option.setAttribute('data-game', repos[i][1]);
    gameSelect.appendChild(option);
}

searchButton.addEventListener("click", onSearchInit, false);
document.body.addEventListener("keypress", onSearchInit, false);

/* If the page was loaded with a PHP-style GET string `?game=<game>&search=<search>`, read it for the search term and perform a search. */
var pos = document.URL.indexOf("?game=");
if (pos != -1) {
    var pos2 = document.URL.indexOf("&search=");
    searchBox.value = decodeURIComponent(document.URL.substring(pos2+8));
    var game = decodeURIComponent(document.URL.substring(pos+6, pos2).toLowerCase());
    if (game == "oblivion") {
        gameSelect.selected = repos[0][1];
    } else if (game == "skyrim") {
        gameSelect.selected = repos[1][1];
    } else if (game == "fallout3") {
        gameSelect.selected = repos[2][1];
    } else if (game == "falloutnv") {
        gameSelect.selected = repos[3][1];
    } else {
        gameSelect.selected = repos[0][1];
    }

    searchButton.click();
} else {
    gameSelect.selected = repos[0][1];
}
