# GitHub sets these, but setting them here so local development environments
# replicate GitHub's behaviour properly.
safe: true
lsi: false

# Enable page redirection
gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
